# Generated by Django 5.1.7 on 2025-03-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('street_address', models.CharField(max_length=255, verbose_name='Улица и номер дома')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('mail_index', models.IntegerField(verbose_name='Почтовый индекс')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('order_notes', models.TextField(verbose_name='Примечания к заказу')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
